### ISSUE TITLE
Support for TrueColors

### ISSUE THREAD

**Issue by afh** [cointop-sh/cointop#117]
From [`termbox.go:122f`](https://github.com/nsf/termbox-go/blob/ed494de23a004d7298fbc78a95595388979cd777/termbox.go#L112-L114) it appears that supporting TrueColor would be possible. I'm happy to have a first stab at a PR, but would appreciate some context around the ui architecture…

There is `fatih/color`, `termbox`, `termui`, `gocui` would it be possible to get an explanation and overview how these interact, from first glance this isn't apparent from the code.

**Comment by miguelmota** [comment]
Great question!

- The TUI view rendering is handled by the `gocui` package. The gocui package is responsible for creating, moving, resizing, and rendering the views. Adding color to view borders and view background is done by modifying attributes on gocui instance. The `pkg/ui` is a wrapper for `gocui` views.
- The `termui` package is only used for generating chart data points as runes. This data points are passed as a string to the chart view to render.
- The `fatih/color` package is used for highlighting text. The sprintf methods are used for adding foreground and background color to text. The `colorscheme.go` file contains helper wrappers for colorscheme. 
- The `termbox` package is utilized by the `termui` package. Cointop doesn't use the termbox package directly.

Hope this clarify things a bit. It may be very possible that TrueColor support can be added to cointop colorschemes but I haven't dug too deep since last time I checked to see if it was doable. 

Let me know if you need help!

@afh

**Comment by afh** [comment]
Thanks for the clarification, @miguelmota, I think this will help me navigate the code-base.

**Comment by lyricnz** [comment]
Anything is possible!

![Screen Shot 2021-10-17 at 11 38 02 am](https://user-images.githubusercontent.com/122371/137605645-fe3dd3d7-b4fa-473a-afb1-8622978167c8.png)

**Comment by lyricnz** [comment]
There is full support for 24-bit colors in themes since #232 .  Use #rrggbb as a color in your theme file.  Also, X11-colors are supported by name.
